version: '3'
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  db:
    build:
      context: ./mysql
      dockerfile: dockerfile
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
