version: '3'

networks:
  medicine-delivery:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    networks:
      - medicine-delivery
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    image: node:16-alpine


  db:
    build:
      context: ./mysql
      dockerfile: dockerfile
    restart: always
    networks:
      - medicine-delivery
    environment:
      MYSQL_ROOT_PASSWORD: bagas371006
      MYSQL_DATABASE: medicine
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
